### ISSUE TITLE
Feature-Request: Processing multiple frequencies.

### ISSUE THREAD

**Issue by tobiasheinz** [notthetup/goertzel-node#1]
Firstly, I'm pretty new to open source contribution so please excuse when doing false assumptions. 

Many use cases need to apply Goertzel to various frequencies. Due to the fact that a asm.js module is a singleton, multiple instances aren't supported.
I created an approve with an array of frequencies as initialization parameter which result in an array of energies. If you're interested, I'm going to create a pull request with a more optimized code?

**Comment by notthetup** [comment]
Cool.  Although I'd think it should go here https://github.com/notthetup/goertzel-filter since that's where the main chunk of code for doing the Goertzel is.

Also asm.js is pretty old (and probably going to be deprecated) now. Might be a good time to look at WebAssembly for the performance gain.

**Comment by tobiasheinz** [comment]
Thanks for the quick reply! Initially I thought about using wasm for this purpose until I found your project. 

I'll try to translate the filter into wasm and add the feature described above afterwards. As soon as I succeeded. I'll create a pull request for the goertzel-filter. But don't expect anything too early

**Comment by rclough** [comment]
Did this ever end up going anywhere? I'm interested in using this to detect multiple frequencies, and I see the latest commit in goertzel-filter is supposed to make it possible, though there wasn't a github release for the version bump

**Comment by notthetup** [comment]
@rclough Thanks. Let me update `goertzel-node` this weekend to come up to speed with `goertzel filter`.

**Comment by notthetup** [comment]
Pushed and published `v2.1.0`. Thanks for reminding me @rclough
